//! The two-dimensional decoder, checked against libtiff.
//!
//! The bug this file exists for was invisible to every other test in the repository. Two
//! coordinate systems meet in a CCITT 2D line: `b1` and `b2` are positions on the
//! *reference* line, while the run lengths a 1D pair carries and the `a1` a vertical mode
//! lands on are counted in the *coding* line from `a0`. Adding a run length to `b1` instead
//! of to `a0` puts the run outside the row whenever the reference line is blank, so no
//! changing element is recorded, the row comes out empty, and every line after it is read
//! against a reference that was never written. Against the corpus that was fifteen
//! recovered rows out of 287, and a specification-derived test could not have seen it: the
//! code was a perfectly good reading of a rule nobody had written down wrong.
//!
//! So the expectations here are not derived from a specification at all. `tiffcp -c g4`
//! wrote every one of these streams and `tiffcp -c none` said what they mean, and what it
//! said was frozen next to the stream by `scripts/make-ccitt-fixtures.py`. The fixtures are
//! checked in, so this runs on a machine with no libtiff at all — which is the point: a
//! test that only runs where the oracle is installed is not a test.
//!
//! Fixture format, little-endian, per file in `fixtures/ccitt-g4/`:
//!
//! | offset | type    | meaning                                  |
//! |--------|---------|------------------------------------------|
//! | 0      | 8 bytes | `MANGLEG4`                               |
//! | 8      | u16     | format version (1)                       |
//! | 10     | u16     | variant: 0 = G.4, 1 = G.3 2D, 2 = G.3 1D  |
//! | 12     | u32     | `/Columns`                               |
//! | 16     | u32     | `/Rows`                                  |
//! | 20     | u32     | compressed byte count                    |
//! | 24     | u32     | expected raster byte count               |
//! | 28     | bytes   | the G.4 stream libtiff encoded           |
//! | …      | bytes   | the raster libtiff decoded from it       |
//!
//! The raster is one bit per sample, most significant bit first, each row padded to a byte,
//! 1 = black. `BlackIs1` is set so the decoder's samples and the raster say the same thing.

#![forbid(unsafe_code)]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::path::{Path, PathBuf};

use mangle_filters::{CcittParams, CcittVariant, ccitt_decode_with_damage};

/// One frozen case: a stream libtiff wrote and the raster libtiff read back from it.
struct Fixture {
    name: String,
    variant: CcittVariant,
    columns: usize,
    rows: usize,
    stream: Vec<u8>,
    /// One bit per sample, 1 = black, rows padded to a byte.
    raster: Vec<u8>,
}

impl Fixture {
    /// The expected row `y` as bytes, 1 = black.
    fn expected_row(&self, y: usize) -> Vec<u8> {
        let stride = self.columns.div_ceil(8);
        let start = y * stride;
        let row = self.raster.get(start..start + stride).unwrap_or(&[]);
        let mut out = Vec::with_capacity(self.columns);
        for x in 0..self.columns {
            let byte = row.get(x >> 3).copied().unwrap_or(0);
            out.push((byte >> (7 - (x & 7))) & 1);
        }
        out
    }

    fn params(&self) -> CcittParams {
        CcittParams {
            variant: self.variant,
            black_is_1: true,
            byte_align: false,
            // libtiff closes a Group 3 stream with two EOLs, and a Group 4 stream with
            // nothing at all: `/EndOfBlock` is how a document says where the data stops.
            end_of_block: self.variant != CcittVariant::G4,
            damaged_rows_before_error: 0,
            columns: self.columns,
            rows: self.rows,
        }
    }
}

/// Every fixture in the repository.
///
/// `None` means the ground truth is not here at all, which is the one thing worth skipping:
/// the fixtures are generated by `scripts/make-ccitt-fixtures.py` and a machine that has
/// never run it has nothing to check against. A fixture that *is* here and does not parse is
/// not a reason to skip — that is a broken test, and a test that reports success while
/// measuring nothing is the failure this whole file was written to avoid.
fn fixtures() -> Option<Vec<Fixture>> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ccitt-g4");
    let Ok(read) = std::fs::read_dir(&dir) else {
        println!(
            "skipped: {} is not readable, so there is no libtiff ground truth to check \
             against. Run scripts/make-ccitt-fixtures.py (needs tiffcp) to produce it.",
            dir.display()
        );
        return None;
    };
    let mut paths: Vec<PathBuf> = read
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ccf"))
        .collect();
    paths.sort();
    if paths.is_empty() {
        println!(
            "skipped: {} holds no .ccf fixtures. Run scripts/make-ccitt-fixtures.py.",
            dir.display()
        );
        return None;
    }
    let cases: Vec<Fixture> = paths.iter().map(|p| parse(p)).collect();
    Some(cases)
}

fn parse(path: &Path) -> Fixture {
    let bytes = std::fs::read(path).expect("a fixture that cannot be read");
    let u16_at = |o: usize| u16::from_le_bytes([bytes[o], bytes[o + 1]]);
    let u32_at = |o: usize| {
        u32::from_le_bytes([bytes[o], bytes[o + 1], bytes[o + 2], bytes[o + 3]]) as usize
    };
    assert_eq!(
        bytes.get(..8).map(|b| b.to_vec()),
        Some(b"MANGLEG4".to_vec()),
        "{} is not a CCITT fixture",
        path.display()
    );
    assert_eq!(
        u16_at(8),
        1,
        "{} is a fixture this reader does not know",
        path.display()
    );
    let variant = match u16_at(10) {
        0 => CcittVariant::G4,
        1 => CcittVariant::G3_2D,
        2 => CcittVariant::G3_1D,
        other => panic!(
            "{} is variant {other}, this reader knows three",
            path.display()
        ),
    };
    let columns = u32_at(12);
    let rows = u32_at(16);
    let stream_len = u32_at(20);
    let raster_len = u32_at(24);
    let stream = bytes
        .get(28..28 + stream_len)
        .expect("a fixture whose stream runs off the end")
        .to_vec();
    let raster = bytes
        .get(28 + stream_len..28 + stream_len + raster_len)
        .expect("a fixture whose raster runs off the end")
        .to_vec();
    assert_eq!(
        raster.len(),
        rows * columns.div_ceil(8),
        "{}: the raster is not {} rows of {} samples",
        path.display(),
        rows,
        columns
    );
    Fixture {
        name: path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned(),
        variant,
        columns,
        rows,
        stream,
        raster,
    }
}

/// `stream` decoded against `raster`, byte for byte, with the first disagreement named.
fn difference(f: &Fixture) -> Result<(), String> {
    let out = ccitt_decode_with_damage(&f.stream, &f.params())
        .map_err(|e| format!("{}: the decoder refused the stream: {e}", f.name))?;
    if out.rows_decoded != f.rows {
        return Err(format!(
            "{}: decoded {} of {} rows ({})",
            f.name,
            out.rows_decoded,
            f.rows,
            out.note.unwrap_or_default()
        ));
    }
    for y in 0..f.rows {
        let got = out.samples.get(y * f.columns..(y + 1) * f.columns);
        let want = f.expected_row(y);
        if got != Some(want.as_slice()) {
            let at = got
                .unwrap_or_default()
                .iter()
                .zip(&want)
                .position(|(a, b)| a != b)
                .unwrap_or(0);
            let ink = want.iter().fold(0usize, |n, b| n + usize::from(*b == 1));
            return Err(format!(
                "{}: row {y} differs at x={at} (we put {}, libtiff put {}; the row has {ink} \
                 black samples). Our row: {}\n     libtiff's: {}",
                f.name,
                got.unwrap_or_default().get(at).copied().unwrap_or(0),
                want.get(at).copied().unwrap_or(0),
                bits(got.unwrap_or_default()),
                bits(&want),
            ));
        }
    }
    Ok(())
}

/// A row as `#` for black and `.` for white, for a message a person can read.
fn bits(row: &[u8]) -> String {
    row.iter()
        .map(|b| if *b == 1 { '#' } else { '.' })
        .collect()
}

/// Every libtiff case, byte for byte.
///
/// One test rather than one per fixture: a case that quietly stopped being checked is a
/// case that broke and nothing noticed, so the count is asserted too.
#[test]
fn two_dimensional_decoding_is_what_libtiff_decodes() {
    let Some(cases) = fixtures() else {
        return;
    };
    let mut failed = Vec::new();
    for f in &cases {
        match difference(f) {
            Ok(()) => println!(
                "{:<22} {:>4}x{:<4} stream {:>6}  matches libtiff byte for byte",
                f.name,
                f.columns,
                f.rows,
                f.stream.len()
            ),
            Err(why) => {
                println!("{why}");
                failed.push(f.name.clone());
            }
        }
    }
    assert!(
        failed.is_empty(),
        "{} of {} libtiff cases differ: {}",
        failed.len(),
        cases.len(),
        failed.join(", ")
    );
    assert!(
        cases.len() >= 10,
        "only {} CCITT fixtures were read; the ground truth is thinner than it should be",
        cases.len()
    );
}

/// The same expectations counted row by row, which is how the corpus defect was measured.
///
/// A corpus page's score moves with how many rows come back right, so this is the number to
/// watch when a change to the decoder makes a document worse.
#[test]
fn every_row_of_every_case_is_recovered() {
    let Some(cases) = fixtures() else {
        return;
    };
    let mut total_rows = 0usize;
    let mut matched = 0usize;
    for f in &cases {
        let out = ccitt_decode_with_damage(&f.stream, &f.params()).expect("a healthy fixture");
        for y in 0..f.rows.min(out.rows_decoded) {
            total_rows += 1;
            if out.samples.get(y * f.columns..(y + 1) * f.columns)
                == Some(f.expected_row(y).as_slice())
            {
                matched += 1;
            }
        }
    }
    println!("rows recovered: {matched} of {total_rows}");
    assert_eq!(
        matched,
        total_rows,
        "{} of {total_rows} rows came back wrong",
        total_rows - matched
    );
}

/// The same rasters, decoded the way a PDF asks for them: `BlackIs1` false.
///
/// The polarity is a separate decision from the decoding, and a decoder that is right about
/// the runs and wrong about the sign still draws a page of ink.
#[test]
fn white_is_one_when_the_document_says_so() {
    let Some(cases) = fixtures() else {
        return;
    };
    for f in &cases {
        let mut p = f.params();
        p.black_is_1 = false;
        let out = ccitt_decode_with_damage(&f.stream, &p).expect("a healthy fixture");
        for y in 0..f.rows.min(out.rows_decoded) {
            let row = out.samples.get(y * f.columns..(y + 1) * f.columns);
            let want: Vec<u8> = f
                .expected_row(y)
                .iter()
                .map(|b| u8::from(*b == 0))
                .collect();
            assert_eq!(
                row,
                Some(want.as_slice()),
                "{}: row {y} has the wrong polarity",
                f.name
            );
        }
    }
}

/// A stream that stops in the middle says so, instead of coming back as a page of nothing.
///
/// A scan that was cut short and a scan of a blank page are the same bytes to a renderer
/// that is handed fifteen rows of white and nothing else. The rows that were there are still
/// handed back — a broken scan has to show what it does contain — but the damage is counted,
/// named, and never quietly passed off as content.
#[test]
fn a_truncated_stream_reports_damage() {
    let Some(cases) = fixtures() else {
        return;
    };
    // A tall case with plenty of rows: half its stream is half its rows, not a prefix of a
    // page that happens to look empty.
    let Some(f) = cases
        .iter()
        .filter(|f| f.rows > 32)
        .max_by_key(|f| f.stream.len())
    else {
        println!("skipped: no fixture with enough rows to truncate");
        return;
    };
    let cut = f.stream.len() / 2;
    let out = ccitt_decode_with_damage(&f.stream[..cut], &f.params()).expect("truncated is data");
    assert!(
        !out.complete,
        "{}: {} rows of a {} row image came back as a complete decode",
        f.name, out.rows_decoded, f.rows
    );
    assert!(
        out.damaged_rows > 0,
        "{}: the stream stopped early and no row was called damaged",
        f.name
    );
    let note = out.note.unwrap_or_default();
    println!("{} truncated to {cut} bytes: {}", f.name, note);
    assert!(
        note.contains(&f.rows.to_string()) || note.contains("damaged"),
        "the note does not say what went wrong: {note:?}"
    );
    assert!(
        out.rows_decoded < f.rows,
        "{}: half the stream gave all {} rows",
        f.name,
        f.rows
    );
    // What was decoded is still a prefix of the whole page, and is still mostly the top of
    // it: the point is to keep the content, not to throw it away.
    for y in 0..out.rows_decoded.min(4) {
        assert_eq!(
            out.samples.get(y * f.columns..(y + 1) * f.columns),
            Some(f.expected_row(y).as_slice()),
            "{}: row {y} of an undamaged prefix is wrong",
            f.name
        );
    }
}

/// Data that is not a fax line at all terminates, and is reported as damaged.
///
/// A mode code that does not match costs no bits, so a decoder that resynchronises by
/// aligning to the next byte can be handed the same broken line for ever. The rows it
/// invents have to be bounded by the data, not by patience.
#[test]
fn a_stream_of_nonsense_terminates() {
    for (name, data) in [
        ("all zeroes", vec![0u8; 64]),
        ("all ones", vec![0xffu8; 64]),
        ("zeroes with a bit set", {
            let mut d = vec![0u8; 64];
            for (i, b) in d.iter_mut().enumerate() {
                *b = if i % 7 == 3 { 0b0000_0101 } else { 0 };
            }
            d
        }),
    ] {
        for variant in [CcittVariant::G4, CcittVariant::G3_1D, CcittVariant::G3_2D] {
            let p = CcittParams {
                variant,
                columns: 64,
                rows: 1000,
                ..Default::default()
            };
            let out = ccitt_decode_with_damage(&data, &p).expect("nonsense is not an error");
            assert!(
                out.rows_decoded <= 1000,
                "{name} {variant:?}: {} rows for a 1000 row image",
                out.rows_decoded
            );
            assert!(
                !out.complete || out.rows_decoded == 1000,
                "{name} {variant:?}: reported a complete decode of {} rows",
                out.rows_decoded
            );
            assert!(
                out.samples.len() == out.rows_decoded * 64,
                "{name} {variant:?}: {} samples for {} rows",
                out.samples.len(),
                out.rows_decoded
            );
        }
    }
}

/// `/DamagedRowsBeforeError` stops the decode at the number the document named.
#[test]
fn damaged_rows_before_error_stops_the_decode() {
    let Some(cases) = fixtures() else {
        return;
    };
    let Some(f) = cases.iter().find(|f| f.rows > 32) else {
        println!("skipped: no fixture with enough rows to damage");
        return;
    };
    let cut = f.stream.len() / 2;
    let mut p = f.params();
    p.damaged_rows_before_error = 2;
    let out = ccitt_decode_with_damage(&f.stream[..cut], &p).expect("truncated is data");
    assert!(
        out.rows_decoded < f.rows,
        "the decode ran to {} rows of {} despite being told to give up",
        out.rows_decoded,
        f.rows
    );
    assert!(out.damaged_rows > 0);
    assert!(!out.complete);
}

/// A stream with no rows at all is empty, and says it is complete rather than broken.
#[test]
fn nothing_in_is_nothing_out() {
    let p = CcittParams {
        columns: 16,
        ..Default::default()
    };
    let out = ccitt_decode_with_damage(&[], &p).expect("empty input");
    assert!(out.samples.is_empty());
    assert_eq!(out.rows_decoded, 0);
    assert_eq!(out.damaged_rows, 0);
    assert!(out.complete, "an empty stream is not a damaged one");
}
